pr=float(input('Qual o preço do seu produto sem desconto? €'))
print('Seu desconto é de 5%')
des=float(pr*0.95)
print('O preço final com desconto é de {}€'.format(des))
pou= float(pr*0.05)
print('Poupou',(pou),'€')
